version: "3"
services:
  web:
    container_name: web 
    restart: always
    build: .
    ports:
      - "8081:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
